server:
  port: 8084

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/fitness-oauth2/protocol/openid-connect/certs

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        - id: activity-service
          uri: lb://activity-service
          predicates:
            - Path=/api/activities/**

        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=/api/recommendations/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,beans,gateway
  endpoint:
    gateway:
      enabled: true
